### ISSUE TITLE
Sitio web de la bitácora

### ISSUE THREAD

**Issue by maikol-solis** [gabosanabria04/BitacorasGrupo-2-CA0204-II-2024-#1]
Hola @gabosanabria04 y @PaolaEspH! 

Revisando su último commit 78b8b986d634345a265b42a3d4d1041570e3c47e, solo quería saber ¿por qué no han generado el sitio web de la bitácora? 

Saludos.

**Comment by PaolaEspH** [comment]
Buenas tardes @maikol-solis;
Un gusto saludarle. En respuesta a su mensaje, este lunes 9 por la mañana, me reúno con mi compañero para generar el sitio web, y se lo estaremos pasando.
Muchas gracias.

**Comment by maikol-solis** [comment]
Gracias Paola. Quedo atento a que generen el sitio y lo compartan por acá. 

Saludos.
