### ISSUE TITLE
Agreguen referencias cruzadas

### ISSUE THREAD

**Issue by maikol-solis** [gabosanabria04/BitacorasGrupo-2-CA0204-II-2024-#3]
Como lo vimos en clase, no pongan a mano las referencias Cuadro 1, Figura 1, etc. 

https://github.com/gabosanabria04/BitacorasGrupo-2-CA0204-II-2024-/blob/5291f9dfee47ac08eef491da976b8c316ee83a1c/bitacora-3.qmd#L601

Deben usar las referencias cruzadas de Quarto 

https://quarto.org/docs/authoring/cross-references.html#floats

**Comment by PaolaEspH** [comment]
Corregido, gracias
