### ISSUE TITLE
Formato incorrecto

### ISSUE THREAD

**Issue by maikol-solis** [gabosanabria04/BitacorasGrupo-2-CA0204-II-2024-#4]
Ojo, este formato no es de Quarto. Posiblemente, ChatGPT lo da así, ya que es de RMarkdown. Deben cambiar esto para que les funcione correctamente. 

https://github.com/gabosanabria04/BitacorasGrupo-2-CA0204-II-2024-/blob/5291f9dfee47ac08eef491da976b8c316ee83a1c/bitacora-3.qmd#L61C1-L61C40

**Comment by PaolaEspH** [comment]
Corregido, gracias.
